server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;

    location = /healthz {
        default_type text/plain;
        return 200 "ok\n";
    }

    location = / {
        return 302 /subway-shanghai/;
    }

    location /subway-shanghai/ {
        try_files $uri $uri/ /subway-shanghai/index.html;
    }
}
